services:
  - type: web
    name: tech-mentorship-backend
    runtime: node
    buildCommand: cd backend && npm install && npx prisma generate && npx tsc
    startCommand: cd backend && node dist/index.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production