services:
  - type: web
    name: tech-mentorship-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && node_modules/.bin/prisma generate && node_modules/.bin/tsc
    startCommand: node dist/index.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production